### ISSUE TITLE
htcondor metapackage has same build id for all boost versions

### ISSUE THREAD

**Issue by duncanmmacleod** [conda-forge/htcondor-feedstock#28]
@conda-forge/core, I'd appreciated some advice in resolving an issue with this feedstock. Currently multiple versions of `python-htcondor` are built for each python version, based on the two `boost` versions supported by `conda-forge-pinning`. However, because the `htcondor` metapackage doesn't explicitly depend upon `boost`, only one version of that package is built, pinning exactly to _one_ of the `python-htcondor` packages.*

*in actual fact multiple `htcondor` packages are built, but they all have the same build ID, so only one of them gets uploaded to anaconda.org - but this is actually a bug in the feedstock that I will resolve at the same time as fixing this issue.

Is the right solution:

1. add `boost` as a `host` requirement for `htcondor` so that multiple versions are produced, that pin to the relevant `python-htcondor` variant?
1. relax the pin for `htcondor` to just `pin_subpackage('python-htcondor', max_pin='x.x.x.x.x')` so that the correct `python-htcondor` version is resolved at install time by the solver?

**Comment by beckermr** [comment]
What is the intent of the exact subpackage pins in the recipe for the htcondor metapackage?

If it is to always use those packages from the exact same build, then adding boost to host is a better solution. 

If instead, you need the same version, but not necessarily the same build, then you could/should relax all of those pins.

**Comment by duncanmmacleod** [comment]
@beckermr, the `htcondor` metapackage is empty, and just depends upon the other components - it's purely a convenience to the users so that they can `conda install htcondor` and probably get what they need.

`python-htcondor` is the only part of that stack to use `boost`, so is the only one built twice. All of the other components use `pin_subpackage(..., exact=True)` so `htcondor-utils` (the command-line executables) and both `python-htcondor` builds will all pin exactly to the same build of `libcondor_utils` - so I think relaxing the pinning will solve this particular issue with no impact to anything else.

**Comment by beckermr** [comment]
OK, so the answer to my question is that you only need the same version, but not the same build. In that case, I would suggest relaxing all of those pins. This will hopefully reduce unneeded churn in peoples' environments.

**Comment by duncanmmacleod** [comment]
Well, I think we want the same build _number_, but not build _ID_. `htcondor` should probably pin to something like `python-htcondor {{ version }} *_{{ number }}`, is that kosher? It seems like `pin_subpackage` doesn't exactly support that.

**Comment by beckermr** [comment]
Why the same build number? Are multiple builds of the same packages at the same version not compatible?

To answer you directly, yes, that kind of pinning is totally fine. However, PRs should almost always bump the build number and there is usually only one build per output, so this is in effect an exact pin.

**Comment by duncanmmacleod** [comment]
> Why the same build number? Are multiple builds of the same packages at the same version not compatible?

@beckermr, I suppose I'm just being careful, and presuming that new builds _will_ in general change something about the library (fix a missing link, enable an optional feature), and I'd rather not deal with users who wend up in a weird situation with packages from different builds in the same environment.

**Comment by beckermr** [comment]
OK. Then this pin `python-htcondor {{ version }} *_{{ number }}` is the best solution. Eliminates the extra package but keeps to the same build.
